version: "3.4"

services:
  mongo:
    container_name: self-service-order-mongo
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD}
    ports:
      - "${DATABASE_MONGO_PORT}:${DATABASE_MONGO_PORT}"
    volumes:
      - ./mongo-data:/data/db
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: always
    ports: 
     - "5672:${RABBITMQ_PORT}"
     - 15672:15672
  order-api:
    container_name: self-service-order-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/usr/app
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_MONGO_HOST=mongo
      - DATABASE_MONGO_USER=${DATABASE_MONGO_USER}
      - DATABASE_MONGO_PASSWORD=${DATABASE_MONGO_PASSWORD}
      - DATABASE_MONGO_NAME=${DATABASE_MONGO_NAME}
      - DATABASE_MONGO_PORT=${DATABASE_MONGO_PORT}
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
